name: Run Django Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  runserver:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run server (for test purpose)
      run: |
        python manage.py migrate
        python manage.py runserver &
        sleep 10  # Give the server time to start
        curl http://127.0.0.1:8000/index/  # Simple test done 